apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: main-i-008f3-6beb6c7
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
  datacenterRef:
    kind: DockerDatacenterConfig
    name: main-i-008f3-6beb6c7
  eksaVersion: v0.0.0-dev+build.7935
  externalEtcdConfiguration:
    count: 1
  gitOpsRef:
    kind: FluxConfig
    name: eksa-test
  kubernetesVersion: "1.28"
  machineHealthCheck:
    nodeStartupTimeout: 10m0s
    unhealthyMachineTimeout: 5m0s
  managementCluster:
    name: main-i-008f3-6beb6c7
  workerNodeGroupConfigurations:
  - count: 3
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: DockerDatacenterConfig
metadata:
  name: main-i-008f3-6beb6c7
  namespace: default
spec: {}

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: eksa-test
  namespace: default
spec:
  branch: aws-eks-anywhere-test-docker-fa2533a0-3583-41ef-ae55-2aa050f76613-2
  clusterConfigPath: aws-eks-anywhere-test-docker-fa2533a0-3583-41ef-ae55-2aa050f76613-2
  git:
    repositoryUrl: ssh://git@github.com/that-jetpack-guy/aws-eks-anywhere-test-docker-fa2533a0-3583-41ef-ae55-2aa050f76613-2.git
  systemNamespace: default

---
